export const TRAINING_TIPS = [
  { emoji: "💪", text: "Priorize movimentos compostos como agachamento, supino e levantamento terra." },
  { emoji: "🏋️", text: "Mantenha 2 a 3 minutos de descanso entre séries em exercícios pesados." },
  { emoji: "🔥", text: "Aqueça o grupo muscular com 1 a 2 séries leves antes da série de trabalho." },
  { emoji: "📊", text: "Para hipertrofia, trabalhe entre 6 e 12 repetições na maioria dos exercícios." },
  { emoji: "⚡", text: "Para força, foque em 1 a 5 repetições com cargas mais altas." },
  { emoji: "🎯", text: "Controle a fase excêntrica — abaixe o peso em 2 a 3 segundos." },
  { emoji: "🔄", text: "Varie ângulos e equipamentos para estimular o músculo de formas diferentes." },
  { emoji: "📈", text: "Aplique sobrecarga progressiva: aumente carga, reps ou séries ao longo do tempo." },
  { emoji: "🧠", text: "Conexão mente-músculo: foque no músculo trabalhado, não só no peso." },
  { emoji: "⏱️", text: "Séries de 30 a 60 segundos de tempo sob tensão também funcionam para hipertrofia." },
  { emoji: "🦵", text: "Não negligencie pernas — treinar membros inferiores acelera ganhos globais." },
  { emoji: "🤝", text: "Peça spot ou use segurança ao treinar perto da falha muscular." },
  { emoji: "📋", text: "Registre carga, séries e reps para garantir progressão consistente." },
  { emoji: "🔁", text: "Drop sets: reduza a carga e continue após a falha para mais estímulo." },
  { emoji: "💥", text: "Rest-pause: descanse 15 segundos e faça mais reps após a falha." },
  { emoji: "🎚️", text: "RIR (Reps in Reserve): pare com 1 a 2 reps antes da falha técnica." },
  { emoji: "🛡️", text: "Priorize forma correta antes de aumentar a carga." },
  { emoji: "🏃", text: "Evite balançar o corpo para roubar reps — controle o movimento." },
  { emoji: "🔩", text: "Use cinto apenas em séries realmente pesadas de agachamento ou terra." },
  { emoji: "🧤", text: "Luvas ou magnésio melhoram a pegada em puxadas e remadas." },
  { emoji: "📐", text: "Amplitude completa de movimento geralmente gera mais estímulo muscular." },
  { emoji: "🪜", text: "Pirâmide crescente: aumente a carga a cada série mantendo as reps." },
  { emoji: "📉", text: "Pirâmide decrescente: comece pesado e reduza a carga nas séries seguintes." },
  { emoji: "🔀", text: "Supersérie: dois exercícios seguidos sem descanso entre eles." },
  { emoji: "🔗", text: "Trisérie: três exercícios consecutivos para o mesmo grupo muscular." },
  { emoji: "🎭", text: "Giant set: quatro ou mais exercícios em sequência para bombardeio muscular." },
  { emoji: "🔄", text: "Bi-set antagonista: treine músculos opostos em sequência, como bíceps e tríceps." },
  { emoji: "⬆️", text: "Partial reps no final da série podem adicionar estímulo extra com segurança." },
  { emoji: "🎪", text: "Isometria: segure a posição mais difícil por 2 a 3 segundos por rep." },
  { emoji: "🫁", text: "Expire na fase de esforço e inspire na fase de retorno." },
  { emoji: "🧱", text: "Core estável: contraia o abdômen em agachamentos e terra para proteger a lombar." },
  { emoji: "🦴", text: "Mobilidade de tornozelo melhora profundidade no agachamento." },
  { emoji: "🎬", text: "Grave seus treinos ocasionalmente para corrigir técnica." },
  { emoji: "📅", text: "Divida o treino em push, pull e legs para equilíbrio muscular." },
  { emoji: "🗓️", text: "Treine cada grupo muscular 2 vezes por semana para otimizar hipertrofia." },
  { emoji: "🌡️", text: "Aumente gradualmente a intensidade — saltos bruscos de carga causam lesões." },
  { emoji: "🎵", text: "Música motivadora pode aumentar esforço percebido e performance." },
  { emoji: "👟", text: "Tênis estável com sola firme ajuda em agachamentos e levantamentos." },
  { emoji: "🧴", text: "Magnésio nos pés ou mãos evita escorregões em terra e agachamento." },
  { emoji: "🔧", text: "Ajuste banco e máquinas à sua biomecânica antes de cada exercício." },
  { emoji: "🎚️", text: "Microplacas permitem progressão mais fina quando o salto de peso é grande." },
  { emoji: "💺", text: "Máquinas são ótimas para isolar músculos e aprender padrões de movimento." },
  { emoji: "🏗️", text: "Peso livre exige mais estabilização e recruta mais fibras musculares." },
  { emoji: "🔄", text: "Deload a cada 4 a 8 semanas: reduza volume ou carga para recuperar." },
  { emoji: "📍", text: "Defina metas SMART: específicas, mensuráveis e com prazo." },
  { emoji: "🎲", text: "Mude o split a cada 8 a 12 semanas para novo estímulo." },
  { emoji: "🧩", text: "Exercícios unilaterais corrigem desequilíbrios entre lados do corpo." },
  { emoji: "🦾", text: "Faixa elástica no aquecimento ativa músculos antes de cargas pesadas." },
  { emoji: "📏", text: "Faixa de movimento parcial pode ser útil em lesões ou platôs específicos." },
  { emoji: "🎯", text: "Treine até a falha técnica, não até perder completamente a forma." },
  { emoji: "🔋", text: "Volume semanal ideal varia, mas 10 a 20 séries por músculo é um bom ponto de partida." },
  { emoji: "🧪", text: "Teste 1RM apenas ocasionalmente — use submaximal para estimar força." },
  { emoji: "🛠️", text: "Pausa na parte inferior do agachamento elimina o reflexo de estiramento." },
  { emoji: "🎚️", text: "Cluster sets: micro-pausas dentro da série permitem mais reps com carga alta." },
  { emoji: "🔄", text: "Negative reps com carga maior exigem parceiro — foque na descida controlada." },
  { emoji: "📦", text: "Blocos de 4 semanas com foco em volume, intensidade e pico funcionam bem." },
  { emoji: "🧭", text: "Comece o treino pelos exercícios mais exigentes quando estiver descansado." },
  { emoji: "🎖️", text: "Consistência supera intensidade extrema esporádica." },
  { emoji: "🫀", text: "Cardio leve no aquecimento não prejudica ganhos se for breve." },
  { emoji: "🏆", text: "Celebre PRs pequenos — cada 0,5 kg a mais é progresso real." },
  { emoji: "🥩", text: "Consuma 1,6 a 2,2 g de proteína por kg de peso corporal para hipertrofia." },
  { emoji: "🍚", text: "Carboidratos abasteceram glicogênio muscular para treinos intensos." },
  { emoji: "🥑", text: "Gorduras boas (abacate, azeite, castanhas) apoiam hormônios e saúde." },
  { emoji: "💧", text: "Beba água ao longo do dia — desidratação reduz força e foco." },
  { emoji: "🍳", text: "Distribua proteína em 4 a 5 refeições para síntese proteica contínua." },
  { emoji: "🥛", text: "Leite, iogurte e queijo são fontes práticas de proteína e cálcio." },
  { emoji: "🍗", text: "Frango, peixe e ovos são proteínas magras versáteis no dia a dia." },
  { emoji: "🫘", text: "Feijão, lentilha e grão-de-bico complementam proteínas vegetais." },
  { emoji: "🍌", text: "Banana pré-treino oferece carboidrato rápido e potássio." },
  { emoji: "🍠", text: "Batata-doce é excelente fonte de carboidrato complexo pós-treino." },
  { emoji: "🥣", text: "Aveia no café da manhã fornece fibras e energia sustentada." },
  { emoji: "🥬", text: "Vegetais coloridos trazem micronutrientes essenciais à recuperação." },
  { emoji: "🍎", text: "Frutas inteiras são melhores que sucos — têm fibras e saciam mais." },
  { emoji: "🧂", text: "Modere o sódio, mas não elimine — importante para hidratação e performance." },
  { emoji: "⚖️", text: "Superávit calórico moderado (200-400 kcal) favorece ganho muscular." },
  { emoji: "📉", text: "Déficit calórico controlado é necessário para perder gordura sem perder músculo." },
  { emoji: "🍽️", text: "Coma em torno do treino: proteína e carboidrato antes e depois ajudam." },
  { emoji: "🕐", text: "Janela anabólica é flexível — o total diário importa mais que o timing exato." },
  { emoji: "🥜", text: "Pasta de amendoim combina gordura boa e calorias densas para quem quer ganhar peso." },
  { emoji: "🐟", text: "Peixes gordos como salmão trazem ômega-3 anti-inflamatório." },
  { emoji: "🌾", text: "Arroz integral tem mais fibras que branco — ambos funcionam conforme a meta." },
  { emoji: "🥗", text: "Salada antes da refeição principal aumenta saciedade e fibras." },
  { emoji: "🍫", text: "Chocolate amargo 70%+ pode ser lanche ocasional com moderação." },
  { emoji: "☕", text: "Cafeína pré-treino melhora foco — evite perto da hora de dormir." },
  { emoji: "🚫", text: "Álcool em excesso prejudica recuperação, sono e síntese proteica." },
  { emoji: "📱", text: "Use app de dieta para estimar calorias até internalizar porções." },
  { emoji: "🥄", text: "Pese alimentos por algumas semanas para calibrar porções visuais." },
  { emoji: "🍞", text: "Pão integral, tapioca e pão sírio são carboidratos práticos no Brasil." },
  { emoji: "🧀", text: "Queijo cottage e ricota são proteínas leves para lanches." },
  { emoji: "🥤", text: "Evite calorias líquidas em excesso — sucos e refrigerantes não saciam." },
  { emoji: "🌰", text: "Castanhas e nozes: porção de um punho fechado por vez." },
  { emoji: "🍝", text: "Massa pós-treino repõe glicogênio — combine com proteína." },
  { emoji: "🥒", text: "Pepino e melancia têm alta água e ajudam na hidratação." },
  { emoji: "🧊", text: "Água gelada durante treino mantém temperatura corporal estável." },
  { emoji: "📊", text: "Macros: ajuste proteína primeiro, depois gordura e carboidrato conforme meta." },
  { emoji: "🍲", text: "Marmitas evitam decisões impulsivas e garantem consistência alimentar." },
  { emoji: "🛒", text: "Liste compras semanais — cozinha saudável começa no mercado." },
  { emoji: "🌙", text: "Refeição leve antes de dormir com proteína pode ajudar recuperação noturna." },
  { emoji: "🥕", text: "Snacks proteicos: ovo cozido, iogurte grego ou shake rápido." },
  { emoji: "🔥", text: "Termogênicos naturais como chá verde têm efeito modesto — dieta vem primeiro." },
  { emoji: "🍬", text: "Doces ocasionais cabem na dieta — consistência no total semanal importa." },
  { emoji: "🧮", text: "Refeição livre semanal pode ajudar aderência psicológica à dieta." },
  { emoji: "🥘", text: "Batch cooking no domingo economiza tempo na semana." },
  { emoji: "🌽", text: "Milho, quinoa e cuscuz diversificam fontes de carboidrato." },
  { emoji: "🍤", text: "Camarão e frutos do mar são proteínas magras e ricas em nutrientes." },
  { emoji: "🥩", text: "Carne vermelha magra 2 a 3 vezes por semana fornece ferro e B12." },
  { emoji: "🫐", text: "Frutas vermelhas são antioxidantes e combinam bem com iogurte." },
  { emoji: "🧃", text: "Hidrate-se: urine clara a amarelo-clara indica boa hidratação." },
  { emoji: "🍵", text: "Chá sem açúcar hidrata e pode substituir parte da água do dia." },
  { emoji: "🥡", text: "Evite frituras frequentes — prefira grelhados, assados e cozidos." },
  { emoji: "📅", text: "Planeje cardápio semanal para não faltar proteína e vegetais." },
  { emoji: "🧈", text: "Manteiga e óleo de coco: use com moderação por serem calóricos." },
  { emoji: "🍇", text: "Uvas e melão são opções de carboidrato pré-treino de digestão rápida." },
  { emoji: "🥒", text: "Pickles e alimentos fermentados podem apoiar saúde intestinal." },
  { emoji: "🌶️", text: "Temperos naturais reduzem necessidade de molhos calóricos." },
  { emoji: "🍳", text: "Ovos inteiros não elevam colesterol na maioria das pessoas saudáveis." },
  { emoji: "🥛", text: "Intolerância à lactose? Prefira whey isolate ou proteínas vegetais." },
  { emoji: "🔄", text: "Refeed day ocasional com mais carboidrato pode ajudar em dietas longas." },
  { emoji: "🎯", text: "Coma proteína em cada refeição — mínimo 25 a 40 g por vez." },
  { emoji: "🧠", text: "Glicemia estável evita picos de fome — combine carboidrato com proteína e fibra." },
  { emoji: "😴", text: "Durma 7 a 9 horas por noite — músculos crescem durante o descanso." },
  { emoji: "🛏️", text: "Horário fixo para dormir regula o ritmo circadiano e melhora recuperação." },
  { emoji: "🌙", text: "Evite telas 1 hora antes de dormir — luz azul atrapalha melatonina." },
  { emoji: "🧊", text: "Gelo 15 min na região inflamada reduz dor aguda pós-treino." },
  { emoji: "♨️", text: "Banho quente antes de dormir relaxa músculos e melhora sono." },
  { emoji: "🧘", text: "Alongamento estático 30 seg por músculo após treino melhora flexibilidade." },
  { emoji: "🌀", text: "Foam roller libera tensão miofascial — 1 a 2 min por grupo muscular." },
  { emoji: "🚶", text: "Caminhada leve no dia off aumenta circulação sem sobrecarregar." },
  { emoji: "📵", text: "Quarto escuro e silencioso — cortinas blackout fazem diferença no sono." },
  { emoji: "⏰", text: "Soneca de 20 min no meio do dia pode restaurar sem atrapalhar noite." },
  { emoji: "🧖", text: "Sauna ocasional pode relaxar, mas hidrate-se bem depois." },
  { emoji: "💆", text: "Massagem esportiva reduz DOMS e melhora amplitude de movimento." },
  { emoji: "🩹", text: "Dor aguda persistente? Descanse e consulte profissional — não treine machucado." },
  { emoji: "🔄", text: "Descanse 48 a 72 h antes de treinar o mesmo músculo com intensidade alta." },
  { emoji: "📉", text: "Reduza volume se dormir mal — corpo não recupera sem sono." },
  { emoji: "🧘‍♂️", text: "Yoga ou mobilidade 2x por semana previne rigidez e lesões." },
  { emoji: "🫁", text: "Respiração diafragmática 5 min acalma sistema nervoso pós-treino." },
  { emoji: "🌿", text: "Ambiente arejado e fresco no quarto melhora qualidade do sono." },
  { emoji: "☕", text: "Evite cafeína após 14h se tiver dificuldade para dormir." },
  { emoji: "🍷", text: "Álcool fragmenta sono REM — evite antes de dormir." },
  { emoji: "📊", text: "HRV e frequência cardíaca em repouso indicam se você está recuperado." },
  { emoji: "🛀", text: "Magnésio Epsom no banho pode relaxar músculos cansados." },
  { emoji: "🧴", text: "Creme de arnica pode aliviar contusões leves — não substitui médico." },
  { emoji: "🏊", text: "Natação leve é recuperação ativa excelente para articulações." },
  { emoji: "🚴", text: "Bike leve no dia de descanso mantém fluxo sanguíneo sem fadiga." },
  { emoji: "🤸", text: "Mobilidade de quadril e ombros previne lesões em agachamento e supino." },
  { emoji: "📅", text: "Agende dias off na semana — descanso é parte do programa." },
  { emoji: "🔇", text: "Earplugs ou ruído branco ajudam quem dorme em ambiente barulhento." },
  { emoji: "🌡️", text: "Quarto entre 18 e 22°C é ideal para sono profundo." },
  { emoji: "🧊", text: "Contraste quente-frio em banho pode acelerar recuperação percebida." },
  { emoji: "🦶", text: "Rolo na planta do pé alivia tensão que sobe pela cadeia posterior." },
  { emoji: "🪢", text: "Banda elástica para mobilidade de tornozelo e ombro diariamente." },
  { emoji: "💤", text: "Cochilos pós-almoço curtos restauram sem atrapalhar treino noturno." },
  { emoji: "🩺", text: "Check-up anual garante que treino intenso é seguro para você." },
  { emoji: "🧠", text: "Estresse crônico eleva cortisol e atrapalha ganhos — gerencie com lazer." },
  { emoji: "📖", text: "Leitura ou meditação antes de dormir acalma a mente hiperativa." },
  { emoji: "🎧", text: "Podcast relaxante pode substituir scroll no celular à noite." },
  { emoji: "🧊", text: "Compressa quente 48h após lesão leve — gelo nas primeiras 24h." },
  { emoji: "🦵", text: "Elevar pernas 10 min após treino de pernas reduz inchaço." },
  { emoji: "🧘", text: "Cat-cow e cobra suave aquecem coluna antes de levantar pesos." },
  { emoji: "⏱️", text: "DOMS leve é normal; dor articular aguda não é — pare e avalie." },
  { emoji: "🔄", text: "Periodize: semanas mais leves permitem supercompensação." },
  { emoji: "🌅", text: "Luz solar pela manhã regula relógio biológico e melhora energia." },
  { emoji: "🛋️", text: "Evite treinar exausto — sono ruim + treino pesado = risco de lesão." },
  { emoji: "🧃", text: "Hidrate-se pós-treino: perda de suor exige reposição de água e eletrólitos." },
  { emoji: "🍌", text: "Potássio de banana ajuda contra cãibras pós-treino intenso." },
  { emoji: "🧂", text: "Sal na refeição pós-treino repõe sódio perdido no suor." },
  { emoji: "🤲", text: "Autmassagem com bola de lacrosse nos glúteos alivia ciático leve." },
  { emoji: "📴", text: "Modo avião à noite reduz distrações e melhora sono profundo." },
  { emoji: "🧘", text: "Respire 4-7-8: inspire 4s, segure 7s, expire 8s para relaxar." },
  { emoji: "🏖️", text: "Férias ativas com descanso real previnem burnout do treino." },
  { emoji: "🩹", text: "Faixa ou kinesio tape podem dar suporte — consulte fisioterapeuta." },
  { emoji: "🔄", text: "Alterne grupos musculares para treinar enquanto outros recuperam." },
  { emoji: "🌊", text: "Nadar ou hidroterapia alivia impacto em joelhos e quadril." },
  { emoji: "🧘", text: "Pigeon pose 1 min por lado abre quadril para agachamentos melhores." },
  { emoji: "💊", text: "Anti-inflamatório só com orientação médica — não mascare lesão." },
  { emoji: "🛌", text: "Colchão e travesseiro adequados são investimento em recuperação." },
  { emoji: "🎯", text: "Escute o corpo: fadiga persistente pede deload, não mais volume." },
  { emoji: "🔍", text: "Identifique pontos fracos e dedique 1 exercício extra por sessão a eles." },
  { emoji: "🌿", text: "Ar puro e caminhada na natureza reduzem cortisol e melhoram humor." },
  { emoji: "🔥", text: "Disciplina supera motivação — treine mesmo nos dias difíceis." },
  { emoji: "🎯", text: "Foque no processo, não só no resultado — consistência vence." },
  { emoji: "📈", text: "Compare-se com você de ontem, não com outros na academia." },
  { emoji: "💎", text: "Pequenos hábitos diários constroem transformações enormes." },
  { emoji: "🏆", text: "Celebre cada PR — progresso incremental é progresso real." },
  { emoji: "🧱", text: "Falhou a dieta? Reinicie na próxima refeição, não na próxima segunda." },
  { emoji: "⏳", text: "Resultados levam meses — paciência é parte do treino." },
  { emoji: "🦁", text: "Saia da zona de conforto — crescimento mora no desconforto controlado." },
  { emoji: "📝", text: "Escreva seus objetivos e releia toda semana." },
  { emoji: "🤝", text: "Treinar com parceiro aumenta accountability e diversão." },
  { emoji: "📸", text: "Fotos de progresso mensais mostram mudanças que a balança esconde." },
  { emoji: "🧠", text: "Visualize o treino antes de entrar na academia — prepare a mente." },
  { emoji: "💬", text: "Mantras simples como 'mais uma rep' ajudam na série final." },
  { emoji: "🚪", text: "Aparecer na academia já é vitória — o resto vem no fluxo." },
  { emoji: "🌱", text: "Um dia ruim não apaga semanas de trabalho consistente." },
  { emoji: "⚔️", text: "Trate treino como compromisso consigo, não punição por comer." },
  { emoji: "🎖️", text: "Marque no calendário cada treino concluído — veja a sequência crescer." },
  { emoji: "🔁", text: "Rotina cria liberdade — horário fixo de treino vira automático." },
  { emoji: "🌟", text: "Admire quem tem o físico que você quer e aprenda com eles." },
  { emoji: "🛡️", text: "Resiliência se treina como músculo — cada obstáculo fortalece." },
  { emoji: "📣", text: "Compartilhe metas com alguém de confiança para manter foco." },
  { emoji: "🎬", text: "Vídeos motivacionais antes do treino podem elevar energia." },
  { emoji: "🧩", text: "Quebre metas grandes em marcos de 4 semanas." },
  { emoji: "💪", text: "Orgulho de terminar treino difícil alimenta confiança fora da academia." },
  { emoji: "🌅", text: "Treinar cedo elimina desculpas do dia — experimente por 2 semanas." },
  { emoji: "🌙", text: "Treino noturno funciona se for seu horário real — consistência importa." },
  { emoji: "🎁", text: "Recompense marcos com algo saudável: roupa nova, equipamento, massagem." },
  { emoji: "🔄", text: "Platô é sinal para ajustar, não desistir." },
  { emoji: "🧭", text: "Seu 'porquê' deve ser pessoal — saúde, família, autoestima." },
  { emoji: "📚", text: "Estudar treino e nutrição empodera e mantém engajamento." },
  { emoji: "🎮", text: "Gamifique: desafios de 30 dias mantêm treino interessante." },
  { emoji: "🤔", text: "Pergunte 'vou me arrepender se não for?' — geralmente a resposta é sim." },
  { emoji: "🌊", text: "Fluxo: perca-se no treino, esqueça problemas por 60 minutos." },
  { emoji: "🏋️", text: "A academia é terapia — suor limpa mente tanto quanto corpo." },
  { emoji: "✨", text: "Acredite no efeito composto: 1% melhor todo dia = transformação." },
  { emoji: "🧗", text: "Obstáculos são degraus — lesão, viagem, trabalho: adapte e volte." },
  { emoji: "📵", text: "Treino sem celular = foco total e sessão mais curta e eficiente." },
  { emoji: "🎵", text: "Playlist exclusiva de treino cria ritual e antecipação positiva." },
  { emoji: "🗣️", text: "Diga 'eu sou alguém que treina' — identidade reforça hábito." },
  { emoji: "🌈", text: "Progresso não é linear — retrocessos fazem parte da jornada." },
  { emoji: "🔑", text: "Chave: aparecer 80% das semanas do ano — isso já te coloca à frente." },
  { emoji: "💡", text: "Inspire-se, mas copie hábitos, não genética alheia." },
  { emoji: "🚀", text: "Momentum: não quebre a corrente de dias consecutivos no início." },
  { emoji: "🧘", text: "Mindfulness no treino: sinta cada rep, esteja presente." },
  { emoji: "🏁", text: "Meta de competição ou evento dá deadline e urgência saudável." },
  { emoji: "📊", text: "Métricas além do peso: medidas, fotos, força, energia." },
  { emoji: "🤲", text: "Seja gentil consigo em dias fracos — volte amanhã mais forte." },
  { emoji: "⚡", text: "Energia gera energia — treinar aumenta disposição no resto do dia." },
  { emoji: "🎯", text: "Elimine 'tudo ou nada' — 20 minutos de treino valem mais que zero." },
  { emoji: "🌍", text: "Corpo saudável permite viver mais e melhor — lembre disso nos dias duros." },
  { emoji: "🔔", text: "Alarme com label 'futuro eu agradece' para levantar para treinar." },
  { emoji: "🧑‍🤝‍🧑", text: "Comunidade online ou presencial mantém você conectado ao objetivo." },
  { emoji: "📖", text: "Diário de treino inclui humor e energia — padrões aparecem com tempo." },
  { emoji: "🎭", text: "Perfeccionismo paralisa — feito é melhor que perfeito." },
  { emoji: "💥", text: "Cansei? Faça aquecimento e decida depois — muitas vezes você continua." },
  { emoji: "🌻", text: "Gratidão pelo corpo que carrega você — treine para fortalecer, não punir." },
  { emoji: "🏔️", text: "Grandes objetivos exigem paciência de montanhista, não de sprinter." },
  { emoji: "🔓", text: "Você não precisa sentir vontade — precisa começar." },
  { emoji: "🎪", text: "Varie treino quando entediar — prazer sustenta longo prazo." },
  { emoji: "🧬", text: "Genética define teto, esforço define onde você chega dentro dele." },
  { emoji: "🥤", text: "Whey protein é conveniente para bater meta proteica pós-treino." },
  { emoji: "⚗️", text: "Creatina monohidratada: 3 a 5 g por dia, todos os dias — a mais estudada." },
  { emoji: "💊", text: "Vitamina D3 se exposição solar for baixa — consulte exames." },
  { emoji: "🐟", text: "Ômega-3 suplementa quando consumo de peixe é insuficiente." },
  { emoji: "🧂", text: "Eletrólitos em treinos longos ou muito quentes previnem cãibras." },
  { emoji: "☕", text: "Cafeína 200-400 mg pré-treino melhora performance — teste tolerância." },
  { emoji: "🌙", text: "Magnésio à noite pode ajudar sono e relaxamento muscular." },
  { emoji: "🍊", text: "Vitamina C apoia imunidade — frutas muitas vezes bastam." },
  { emoji: "🥛", text: "Caseína antes de dormir libera proteína lentamente durante a noite." },
  { emoji: "🌾", text: "Whey concentrado é econômico; isolate serve melhor para intolerantes." },
  { emoji: "💧", text: "Creatina não precisa de fase de carga — dose diária constante funciona." },
  { emoji: "📦", text: "Suplemento complementa dieta — comida real vem primeiro." },
  { emoji: "🏷️", text: "Escolha marcas com selo de qualidade e transparentes em rótulo." },
  { emoji: "🚫", text: "Evite proprietary blends que escondem doses dos ingredientes." },
  { emoji: "🧪", text: "Beta-alanina causa formigamento — normal e inofensivo." },
  { emoji: "⚡", text: "Pré-treino combina cafeína, beta-alanina e citrulina — use com moderação." },
  { emoji: "🔄", text: "Ciclar cafeína 1 semana off a cada 8 evita tolerância." },
  { emoji: "💪", text: "BCAA é opcional se proteína total diária já é alta." },
  { emoji: "🌱", text: "Proteína vegetal (ervilha+arroz) funciona tão bem quanto whey para muitos." },
  { emoji: "🍫", text: "Barra proteica é snack prático — leia rótulo por açúcar escondido." },
  { emoji: "🧃", text: "HMB pode ajudar em dietas agressivas de cutting — efeito modesto." },
  { emoji: "🦴", text: "Colágeno apoia articulações e pele — não substitui proteína completa." },
  { emoji: "🧬", text: "Multivitamínico cobre lacunas se dieta for restrita ou variada demais." },
  { emoji: "🩸", text: "Ferro só suplemente com deficiência confirmada em exame." },
  { emoji: "🌿", text: "Ashwagandha pode reduzir cortisol e stress — evidência moderada." },
  { emoji: "💊", text: "ZMA (zinco, magnésio, B6) popular para sono — benefício varia." },
  { emoji: "🥄", text: "Creatina dissolve melhor em líquido morno ou shake." },
  { emoji: "📅", text: "Consistência na creatina importa mais que timing exato." },
  { emoji: "🚰", text: "Creatina pode reter água intramuscular — ganho de peso inicial é normal." },
  { emoji: "🏥", text: "Consulte médico antes de suplementos se tiver condição de saúde." },
  { emoji: "👶", text: "Grávidas e lactantes: evite suplementos sem orientação profissional." },
  { emoji: "💊", text: "Vitamina B12 essencial para veganos — suplementação recomendada." },
  { emoji: "🌞", text: "Vitamina D: 1000-4000 UI comum — dose ideal depende de exame." },
  { emoji: "🧊", text: "Glutamina tem evidência fraca para hipertrofia — prioridade baixa." },
  { emoji: "🔬", text: "HMB, arginina e outros boosters têm efeito pequeno na prática." },
  { emoji: "🍵", text: "Chá verde em cápsula equivale a extrato — moderação em cafeína total." },
  { emoji: "⚖️", text: "Termogênicos não substituem déficit calórico na perda de gordura." },
  { emoji: "🥤", text: "Shake pós-treino: 25-40 g proteína + carboidrato se treino foi intenso." },
  { emoji: "🕐", text: "Whey rápido pós-treino; caseína ou comida sólida antes de dormir." },
  { emoji: "📦", text: "Compre suplemento pelo custo por dose, não só preço do pote." },
  { emoji: "🧴", text: "Armazene suplementos em local seco e fresco — validade importa." },
  { emoji: "🔄", text: "Não misture muitos suplementos novos de uma vez — teste um por vez." },
  { emoji: "💊", text: "Cápsulas vs pó: pó é mais barato; cápsulas são convenientes." },
  { emoji: "🌾", text: "Maltodextrina ou dextrose pós-treino repõe glicogênio barato." },
  { emoji: "🧃", text: "Bebida isotônica caseira: água, sal, mel e limão para treinos longos." },
  { emoji: "🦐", text: "Krill oil alternativa ao fish oil para ômega-3." },
  { emoji: "🍄", text: "Vitamina D3 + K2 juntas podem otimizar absorção de cálcio." },
  { emoji: "💉", text: "Nada substitui alimentação — suplemento é 5% do resultado, não 95%." },
  { emoji: "📋", text: "Liste suplementos que usa e informe médico em consultas." },
  { emoji: "🧒", text: "Adolescentes: foco em comida e sono; creatina tem evidência segura em estudos." },
  { emoji: "🏋️", text: "Citrulina malato 6-8 g pré-treino pode reduzir fadiga e pump." },
  { emoji: "🩹", text: "Suplementos anti-inflamatórios naturais não substituem descanso." },
  { emoji: "🔍", text: "Procure INMETRO ou certificações em produtos nacionais." },
  { emoji: "💰", text: "Suplemento caro não é necessariamente melhor — leia composição." },
  { emoji: "🌡️", text: "Não exponha whey ao calor — proteína denatura e sabor piora." },
  { emoji: "🥛", text: "Intolerante à lactose: whey isolate, proteína de ovo ou ervilha." },
  { emoji: "📊", text: "Exames de sangue guiam suplementação inteligente, não marketing." },
  { emoji: "🎯", text: "Priorize: proteína, creatina, vitamina D, ômega-3 — resto é opcional." },
  { emoji: "🧠", text: "Nootrópicos para foco têm evidência mista — sono e dieta vêm primeiro." },
  { emoji: "✅", text: "Suplementação básica bem feita cobre 90% das necessidades de atletas amadores." },
] as const;

export type TrainingTip = (typeof TRAINING_TIPS)[number];
